id: P009091
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3711
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ་ཞེས་བྱ་བའི་མཆན་འགྲེལ་
  author: ''
  volumes:
    0303620982e9464f9ce7805004b781bc:
      image_group_id: I1KG3797
      title: ''
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
